### ISSUE TITLE
react-map-gl StaticMap does not receive viewport properties from Nebula

### ISSUE THREAD

**Issue by romaxa** [uber/nebula.gl#157]
#### Describe the bug
Nebula/DeckGL does not pass viewport parameters to it's child "StaticMap"

Working setup with deck only:
```
<DeckGL
   initialViewState={viewport}
   layers={[]}>
    <StaticMap mapStyle={RasterTileStyle(['https://a.tile.openstreetmap.org/{z}/{x}/{y}.png'])} />
</DeckGL>
```

Not working setup with Nebula wrapper:
```
  <Nebula ref={nebula => nebula}
              viewport={viewport}
              layers={[]}>
        <StaticMap mapStyle={RasterTileStyle(['https://a.tile.openstreetmap.org/{z}/{x}/{y}.png'])} />
      </Nebula>
```

Example: https://github.com/romaxa/fusion-app-nebula

**Comment by ibgreen** [comment]
The first example probably works because deck.gl does some prop injection of `viewState` on its children.

However, since you have the viewport available, you should be able to add a `viewState={viewport}` prop to the StaticMap in the second example, telling it what to show,

deck.gl and react-map-gl have been replacing the `viewport` prop with `viewState`, recommend nebula does the same for consistency.

**Comment by georgios-uber** [comment]
Thanks @romaxa
