### ISSUE TITLE
Freehand Draw Mode

### ISSUE THREAD

**Issue by baxter1707** [uber/nebula.gl#172]
#### Feature request
Free Hand Draw Mode
#### Background 
The ability to draw on the map without having to click to add a point. The line would trace and be added based on where your mouse moved on top of the map. 

Thank you!

**Comment by supersonicclay** [comment]
We'd welcome a pull request for this. It shouldn't be too difficult to implement as a custom `ModeHandler`.  It will likely be pretty similar to `DrawLineStringHandler` except the points will be added in `handlePointerMove` rather than `handleClick`. The one thing to keep in mind is that you may want to debounce the adding of points otherwise, you could end up with a LineString with many thousands of points. Perhaps even make the debounce time something a user can specify in `modeConfig`.

**Comment by baxter1707** [comment]
Thank you for this input! I'll look into this using your suggestions.
