### ISSUE TITLE
react-map-gl-draw - new feature gets cleared while zooming when being created

### ISSUE THREAD

**Issue by peetjvv** [uber/nebula.gl#408]
#### Describe the bug
When you're busy creating a new feature (only tested with DrawLineStringMode) your feature will be cancelled when zooming on the map.

#### Actual Result
When busy creating a feature, the feature will be cancelled when zooming on the map.

#### Expected Result
Being able to change your zoom while creating a feature.

#### Reproduce Steps
 1. Set editor mode to DrawLineStringMode
 2. Start creating a feature
 3. Scroll mouse wheel
 4. Your feature being created will clear and your work will be lost

#### Screenshots
Pre scroll:
![image](https://user-images.githubusercontent.com/22648295/83023585-619ef000-a02d-11ea-8bef-3963703ffcf8.png)

Post scroll:
![image](https://user-images.githubusercontent.com/22648295/83023670-81ceaf00-a02d-11ea-8012-cbb585310cb6.png)

#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by peetjvv** [comment]
I've pushed some example code for this bug to this repo: https://github.com/peetjvv/map-gl-draw-test-js

**Comment by timminata** [comment]
It seems the reason is it clearing is because on component state update is is clearing the edit mode and calling `new DrawLineStringMode()`.
To fix this you can have `const editMode = new DrawLineStringMode()` and use that `mode={editMode}`.
I'm not sure if this is the intended behaviour of the library.
I think it is misleading that the polygon example [here ](https://nebula.gl/docs/api-reference/react-map-gl-draw/react-map-gl-draw) [(CodeSandbox)](https://codesandbox.io/s/react-map-gl-draw-example-f6x32?file=/src/app.js) has the same issue. Anyone following that code example is going to have a problem.
Please could the authors shed some light on the correct approach here?

**Comment by supersonicclay** [comment]
This is the intended behavior. There is state persisted in the modes. And there are optimizations done within nebula.gl and deck.gl based on shallow equality comparisons between renders. So, since it is a new mode instance on every render, it clears state over and over.

Good catch on the docs.

**Comment by timminata** [comment]
Thanks for the explanation and updating the docs!

**Comment by peetjvv** [comment]
Thanks from my side as well!
