### ISSUE TITLE
App build crush when @nebula.gl/layers added as dependecy 

### ISSUE THREAD

**Issue by Akiyamka** [uber/nebula.gl#418]
#### Describe the bug
App build crush when `@nebula.gl/layers` added as dependecy 

#### Actual Result
```
./node_modules/@nebula.gl/layers/dist-es6/index.js
 └─ ./node_modules/@nebula.gl/layers/dist-es6/layers/path-marker-layer/path-marker-layer.js

Module not found: Error: Can't resolve '@deck.gl/mesh-layers' in './node_modules/@nebula.gl/layers/dist-es6/layers/path-marker-layer'

```
#### Expected Result
Nebula should not break the build (must install own dependencies or declare it as peer dependency)

#### Reproduce Steps
```
yarn add @nebula.gl/layers
yarn build
```
#### Workaround
```
yarn add @deck.gl/mesh-layers
```
#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by GoCardsCai** [comment]
The `@deck.gl/mesh-layers` is in the peer dependencies to avoid package conflicts and it is set in the [package.json](https://github.com/uber/nebula.gl/blob/master/modules/layers/package.json). 

The problem is that NPM doesn't automatically installs the peer dependencies of a dependency and only shows the warning of peer package being missing. https://stackoverflow.com/questions/35207380/how-to-install-npm-peer-dependencies-automatically. So we might still use the workaround if `@deck.gl/mesh-layers` is not directly used in your project.
