### ISSUE TITLE
"mode" does not exist in type "CompositeLayerProps<any>".

### ISSUE THREAD

**Issue by namndtth** [uber/nebula.gl#462]
#### Describe the bug
I'm using an example from [https://nebula.gl/docs/get-started/basic-usage](url) written by typescript. After installing nebula.gl and its dependencies, I compiled the program and got the error ```Can't import the named export 'diff' from non EcmaScript module (only default export is available)```, so I decided to remove ```./node_modules/@turf/difference/index.mjs``` file.
Then i recompiled the program. But  now it announcing an error that 'mode' does not exist in type 'CompositeLayerProps<any>'.

#### Actual Result

Typescript error as following message:
```Argument of type '{ id: string; data: any; mode: string; onEdit: ({ updatedData }: { updatedData: any; }) => void; }' is not assignable to parameter of type 'CompositeLayerProps<any>'.```
```Object literal may only specify known properties, and 'mode' does not exist in type 'CompositeLayerProps<any>'.```

#### Expected Result

App run successfully.

#### Reproduce Steps
- Install nebula through yarn.
- Copy an example from link above.
- Compile the program using typescript.
#### Screenshots

![image](https://user-images.githubusercontent.com/42760423/90847467-c354c900-e394-11ea-8680-49b5abfb0380.png)

#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

Thanks for any help.

**Comment by supersonicclay** [comment]
This is actually an issue with turf. You can downgrade the version of turf or remove the `*.mjs` files.

See these issues:
https://github.com/uber/nebula.gl/issues/333
https://github.com/uber/nebula.gl/issues/64
https://github.com/Turfjs/turf/issues/1383

**Comment by namndtth** [comment]
@supersonicclay Thanks for you help!

**Comment by auzmartist** [comment]
As a third solution, I was able to work around this issue by adjusting my webpack `config.resolve.extensions` to prepend '.js', essentially instructing webpack to resolve turf's index.js files BEFORE index.mjs files. [Webpack Docs Reference](https://webpack.js.org/configuration/resolve/#resolveextensions)

With React, this requires you use react-app-rewrite with a config-overrides.js file looking something like this:
```js
module.exports = function override(config, env) {
  // ...
  config.resolve.extensions = ['.js', ...config.resolve.extensions];
  return config;
}
```

If you have webpack config access in your project:
```
const config = {
  // ...
  resolve {
    // ...
    extensions: ['.js', /* your other extensions */],
  }
}
```

I prefer this solution since I don't need to worry about locking into on old turf version or modifying local files with some npm post-install script.

**Comment by joenordlingNeerAI** [comment]
I have followed all the steps above; however, I still have these issues. Any other solutions?
