### ISSUE TITLE
Ability to see radius/area while drawing circle/polygon

### ISSUE THREAD

**Issue by Ashar2shahid** [uber/nebula.gl#464]
#### Feature request
Hi Would like the ability to see the radius of the circle while drawing it, is this currently possible? maybe add this as an optional prop?

#### Background 
While drawing any polygon or circle would like to see the area/perimeter/radius while drawing it. Having to use a different mode to measure the area/length is counter intuitive because sometimes a user might just want to select a circle of 1km radius but currently this information is not displayed while drawing.

**Comment by supersonicclay** [comment]
nebula.gl provides the ability to provide custom modes. You can even extend the existing modes provided by nebula. You can extend the `DrawCircleFromCenterMode` and provide a `getTooltips` function in order to provide whatever text in whatever place you'd like. See the measurement modes to see how `getTooltips` works.

https://github.com/uber/nebula.gl/blob/master/modules/edit-modes/src/lib/measure-distance-mode.ts
